spring:
  application:
    name: tech-spring-cloud-api-gateway-service
  cloud:
    gateway:
      routes:
       - uri: http://localhost:8700/
         predicates:
          - Path=/product-enquiry/**
          
    
    
server:
  port: 8900